#!/usr/bin/with-contenv bash

if [ ${DISABLE_NB} = false ]; then \
    echo "executing jupyter lab..."
    cd "${HOME}"

    exec jupyter lab \
        --notebook-dir="${HOME}" \
        --ip=0.0.0.0 \
        --no-browser \
        --allow-root \
        --port=${JUPYTERLAB_PORT} \
        --ServerApp.open_browser=False \
        --ServerApp.token="" \
        --ServerApp.password="" \
        --ServerApp.allow_origin="*" \
        --ServerApp.base_url="${NB_PREFIX}" \
        --ServerApp.authenticate_prometheus=False
fi
